"""initial_schema

Revision ID: 84eb493cad9e
Revises: 
Create Date: 2026-03-18 10:18:38.862369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84eb493cad9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('inviter', sa.String(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip alter_column for SQLite as it already has the columns from raw SQL init
    if op.get_context().dialect.name != 'sqlite':
        op.alter_column('risk_audit', 'risk_id', existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        op.alter_column('risk_profile_audit', 'audit_id', existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        op.alter_column('teams', 'id', existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        op.alter_column('users', 'email', existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    # ### end Alembic commands ###
